Repository jaspermayone/website, pull requests merged in 2024-09, with the labels that each got.

#35 replace images with SVG icons
  .gitignore
  package.json
  src/pages/index.tsx
  yarn.lock
Labels: enhancement, size/L

#36 Fix meta tags
  src/pages/_app.tsx
  src/pages/_document.tsx
  yarn.lock
Labels: enhancement, size/L

#40 add threads link
  src/components/ui/accordion.tsx
  src/components/ui/photos.tsx
  src/components/ui/tooltip.tsx
  src/pages/index.tsx
Labels: enhancement, size/M

#45 Delete .github/workflows/dependency-review.yml
  .github/workflows/dependency-review.yml
Labels: size/S
